blank_issues_enabled: false
contact_links:
  - name: Security Report
    url: https://github.com/Ahlstarr-Mayjishan/Rayfield-mod/security/advisories/new
    about: Please report security vulnerabilities privately.
